Don't build cryptoauthlib tests on Mbed OS
cryptoauthlib tests contain their own copy of Unity, which conflicts
with the copy of Unity provided by Mbed OS. The tests also depend on
some symbols that are undefined in our current configuration. As
cryptoauthlib is tested elsewhere, remove the cryptoauthlib tests from
our example.

    Error: L6218E: Undefined symbol tng_get_device_pubkey (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atca_test.o).
    Error: L6218E: Undefined symbol tng_get_type (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atca_test.o).
    Error: L6218E: Undefined symbol g_tng22_cert_def_1_signer (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol g_tng22_cert_def_2_device (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_device_public_key (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_max_device_cert_size (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_max_signer_cert_size (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_read_device_cert (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_read_signer_cert (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_root_cert (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_root_cert_size (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_root_public_key (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Error: L6218E: Undefined symbol tng_atcacert_signer_public_key (referred from BUILD/K64F/ARMC6/mbed-os-atecc608a/mbed-cryptoauthlib/cryptoauthlib/test/tng/tng_atcacert_client_test.o).
    Finished: 0 information, 13 warning and 13 error messages.